# Generated by Django 4.2.21 on 2025-07-14 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventapp', '0001_initial'),
        ('treeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='family',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='treeapp.family'),
        ),
        migrations.AddField(
            model_name='event',
            name='family',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='treeapp.family'),
        ),
    ]
