# Generated by Django 4.2.21 on 2025-07-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marriage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
