# Generated by Django 4.2.21 on 2025-05-28 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='father',
        ),
        migrations.RemoveField(
            model_name='person',
            name='mother',
        ),
        migrations.RemoveField(
            model_name='person',
            name='spouse',
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_marriage', models.DateField(blank=True, null=True)),
                ('husband', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_husband', to='treeapp.person')),
                ('wife', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_wife', to='treeapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marriage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='treeapp.marriage')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='treeapp.person')),
            ],
        ),
    ]
