# Generated by Django 4.2.21 on 2025-07-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeapp', '0002_marriage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marriage',
            name='description',
        ),
        migrations.AddConstraint(
            model_name='marriage',
            constraint=models.UniqueConstraint(fields=('husband', 'wife'), name='unique_husband_wife'),
        ),
    ]
