# Generated by Django 4.2.21 on 2025-07-16 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treeapp', '0004_alter_marriage_family_alter_marriage_husband_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutarticle',
            name='family',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='about_articles', to='treeapp.family'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='family',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='app_configs', to='treeapp.family'),
        ),
        migrations.AlterField(
            model_name='child',
            name='family',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children_family', to='treeapp.family'),
        ),
        migrations.AlterField(
            model_name='child',
            name='marriage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='treeapp.marriage'),
        ),
        migrations.AlterField(
            model_name='child',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='treeapp.person'),
        ),
        migrations.AlterField(
            model_name='imagecarousel',
            name='family',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='carousels', to='treeapp.family'),
        ),
        migrations.AlterField(
            model_name='person',
            name='family',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='members', to='treeapp.family'),
        ),
    ]
